version: 2

builds:
  - id: bundr
    binary: bundr
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    goos: [linux, darwin]
    goarch: [amd64, arm64]

archives:
  - {}

checksum:
  algorithm: sha256

snapshot:
  version_template: "{{incpatch .Version}}-next"

release:
  prerelease: auto

brews:
  - name: bundr
    homepage: "https://github.com/youyo/bundr"
    description: "AWS Parameter Store と Secrets Manager を統合する単一バイナリ Go CLI"
    license: "MIT"
    repository:
      owner: youyo
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    install: |
      bin.install "bundr"
    test: |
      system "#{bin}/bundr", "--help"
